travis:
  secure:
    BINSTAR_TOKEN: hvlHiFriL4RHOLM5hsTMe+mvLQFmZ6GIGXHn/1Wf/9Ial3FFPA+Hh4qiRpj5d8um8IwMg7XCHX5JNDkGieP3YR/qv1RtPSfywnfoR0lcwIHdNb16CI7pL/jZ0o57pgzpA5kEpncSi+exxoRoBX+NBQYG1F8p0HOePtE2yPZexoaqaPZBLyvjdYF0g8+B61AKL1aBfxeYXZN/DJO3hJeYPglF0R4XDbAZO6epfyl0F5XfrhjlzFdbCAhXj2cHFDcU+IHncbKXO/9I7qGZTKTVTYtu7/q6xT5Un+EEb5ltNK/Mljq0XaSi2W14061KG8n38qkNYpG+ohSUCt5pZYHfEAe8rkUmkETniRoQ5B6EyR+PueFPfR0yDS7scYSdRx5Jjz9Qv92UzNcnEBUM5GiOzpwG38BwXiGVGLyV9sCIWgcUIKZ/9C+J0FsetFQndA+hTDmMZBaPU8I5ycNUyP9QDrHIehnCytw1J0mGp8reDBhP1gid1rO9OdkBr3keC3C/ETTW5PjddtCB0UlxvsluA7V5S4Bkf/7x9/46/UNNpficY9z5RfyeEpRmdCHw2B9x5YZVfIeXRlM0pmkKrBPMMtQrBV1ZPraFPekXBzb3aEStr9q4iBbxYgkbCJI2UJAFOBWW2FPPPYnqXzAMEGb+mkMxrVidEJNtw1s9Kv1OAvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
