appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZVX+wSdhuAB/mwad3F0rdpzSAlIHGGHFIsbKuhwvwoipGH07XrS0jDnlUdlKTpDtiBLwV35xEnqBJJSXc/6LlHvU5ofWUQp/kclF/8cQNQgpHZftjKGbMpm0AZPVaKjcGdLFsnQXQscsrbJPVoC0G8Z5LBK0N9JzgzBeHG2iTraBsm4p6ar4Y2X6FqNx4LQyg2h50yhPOskGOdkoSSAc3GTPsB3pYmgNQXrYeNwdV1UWkimVOR8T44Ns8W3i0zEGCv4rBjX34UTBpmjI4fFF2TBCRBv4Qq0jP7zGrsXQs6jWfrrwflaJfa2X8j+MtJ+t4kJ/zWS77+Fu5aSfGADxkSjRlmBKxXiLwMNYNU9RJ6B1FKEk/LKl2+E0GhcvueY61FJiLH2ZA6DgoBzBTPP9g5xSbKFbIgXTY0oJjrja5+k+Kij1eMaSKLSVe+Ugs+y1VNQ4R8S8GQN/On8L6KAWPCcVpZy940EQPBU9aNSJZj1r7TAjQJ/I33ekc7YRPhdHP/5cB/HTU0QlSwfhRZ3bemxHAg/mcqbZRqqzfMfdRefPnfJdPEcepJokZDPbRpkscz8+4FnAYKphdUKQ8S8yLYFZQ3D4DBr2lbHOwz598GOCSxgV24Sgc+EDT+DUhBkH3TRUoUuvcjU41ueAHLDSZulC0X90IYM3vQMVXRautL4=}
